# Generated by Django 4.0.4 on 2022-05-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q', '0003_alter_comment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
